package com.andavarmillklr.oil.masalas.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * User Entity - Represents a registered user in the Andavar platform.
 *
 * This table stores all user accounts, including both regular customers
 * and admin users. The 'role' field determines what actions a user can perform.
 *
 * Table name: users
 *
 * Fields:
 *   - id:         Unique identifier for each user (auto-generated)
 *   - mobile:     Mobile phone number used for login (must be unique)
 *   - password:   BCrypt-hashed password (never stored in plain text)
 *   - fullName:   Display name of the user
 *   - email:      Optional email address
 *   - role:       Either "ROLE_USER" or "ROLE_ADMIN"
 *   - createdAt:  Timestamp when the account was created
 */
@Entity
@Table(name = "users")
public class User {

    // ========== Primary Key ==========

    /** Unique ID for this user, auto-generated by the database */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ========== Login Credentials ==========

    /** Mobile number used as the username for login. Must be unique. */
    @Column(nullable = false, unique = true, length = 15)
    private String mobile;

    /** BCrypt-encrypted password. Never stored as plain text. */
    @Column(nullable = false)
    @com.fasterxml.jackson.annotation.JsonIgnore
    private String password;

    // ========== Profile Information ==========

    /** Full name of the user (displayed in orders, reviews, etc.) */
    @Column(name = "full_name", length = 100)
    private String fullName;

    /** Optional email address for the user */
    @Column(length = 100)
    private String email;

    // ========== Role & Permissions ==========

    /**
     * Role determines what actions the user can perform.
     * "ROLE_USER"  -> Can browse, add to cart, place orders, write reviews
     * "ROLE_ADMIN" -> Can manage products, view all orders, manage notifications
     */
    @Column(nullable = false, length = 20)
    private String role = "ROLE_USER";

    // ========== Timestamps ==========

    /** When this user account was created */
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    /**
     * This method runs automatically BEFORE the entity is saved to the database
     * for the first time. It sets the createdAt timestamp to the current time.
     */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }

    // ========== Constructors ==========

    /** Default constructor (required by JPA/Hibernate) */
    public User() {
    }

    /**
     * Constructor to create a new user with all required fields.
     *
     * @param mobile   The user's mobile number (used for login)
     * @param password The BCrypt-hashed password
     * @param fullName The user's display name
     * @param role     The user's role ("ROLE_USER" or "ROLE_ADMIN")
     */
    public User(String mobile, String password, String fullName, String role) {
        this.mobile = mobile;
        this.password = password;
        this.fullName = fullName;
        this.role = role;
    }

    // ========== Getters and Setters ==========

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
